### PR TITLE
Added api.irail.be

### PR DESCRIPTION
**Pull request by pietercolpaert**

### CODE REVIEW

**Comment by juliuste** [comment]
👍❤️🇧🇪

**Comment by juliuste** [comment]
@pietercolpaert Is there an up-to-date GTFS for irail.be?

**Comment by pietercolpaert** [comment]
Not publicly available at this point... You can however request one through this form: http://www.belgianrail.be/en/customer-service/FAQ/public-data.aspx

We are trying to convince the SNCB that this step is an unnecessary hurdle (quod erat demonstrandum), but for the time being, that is the state of the art :-)

**Comment by pietercolpaert** [comment]
There is a github repository for the stations list though: https://github.com/irail/stations

Mind that iRail is a volunteer project to make the train schedules better accessible to digital creatives. We are in contact with the Belgian railway company, but we are not affiliated.

**Comment by juliuste** [comment]
Thank you! 🙂 So I assume that [this](https://gtfs.irail.be/nmbs/) is discontinued ATM?

**Comment by pietercolpaert** [comment]
For the moment it is. We might re-launch it next year, after we launched a new style of API based on Linked Connections (http://linkedconnections.org)

**Pull request merged**
